- name: join worker to cluster (1/2)
  ansible.builtin.template:
    src: ./templates/kubeadm-joinconf.j2
    dest: /tmp/kubeadm-joinconf.yaml
    owner: root
    group: root
    mode: "0644"

- name: join worker to cluster (2/2)
  ansible.builtin.shell: |
    kubeadm join --config /tmp/kubeadm-joinconf.yaml