---
- name: AWS self-managed k8s cluster configuration
  hosts: all
  become: true
  roles:
    - role: node-prepare
      tags:
        - node-prepare
    - role: cluster-setup
      tags:
        - cluster-setup
    - role: post-tasks
      tags:
        - post-tasks
  vars:
    etcdctl_version: "3.5.6"
    cluster_version: "1.25.8-00"
    containerd_version: "1.6.20-1"
    pod_net: "10.100.0.0/16"
    svc_net: "10.200.1.0/24"
    traefik_ingress: true
    metallb: true
    rook_ceph: true
    k8s_dash: true
    metrics_server: true
    traefik_dashboard_host: "traefik.k8s.glowcow.xyz"
    ceph_dashboard_host: "ceph-dash.k8s.glowcow.xyz"
    k8s_dashboard_host: "dashboard.k8s.glowcow.xyz"