---
- name: AWS self-managed k8s cluster configuration
  hosts: all
  become: true
  roles:
    - role: node-prepare
      tags:
        - node-prepare
        - cluster-setup
    - role: cluster-setup
      tags:
        - cluster-setup
    - role: post-tasks
      tags:
        - post-tasks
        - cluster-setup
        - node-add
  vars:
    - etcdctl_version: "3.5.6"
    - cluster_version: "1.25.5-00"
    - containerd_version: "1.6.14-1"
    - pod_net: "10.100.0.0/16"
    - svc_net: "10.200.1.0/24"
    - nginx_ingress: true
    - metrics_server: true