- name: install kube packages on master
  ansible.builtin.apt:
    pkg:
    - kubelet={{cluster_version}}
    - kubeadm={{cluster_version}}
    - kubectl={{cluster_version}}
    update_cache: yes

- name: init kubernetes cluster on master (1/2)
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr={{pod_net}} --service-cidr={{svc_net}} --ignore-preflight-errors="NumCPU"

- name: init kubernetes cluster on master (2/2)
  ansible.builtin.shell: |
    echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /etc/environment

- name: install CNI (1/2)
  ansible.builtin.template:
    src: ./templates/cni-flannel.j2
    dest: /tmp/cni-flannel.yml
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: install CNI (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/cni-flannel.yml
  run_once: true

- name: generate join token
  ansible.builtin.shell: |
    kubeadm token create --print-join-command
  register: kubeadm_join_out
  run_once: true

- name: set kubeadm_join var
  ansible.builtin.set_fact:
    kubeadm_join: "{{kubeadm_join_out.stdout}}"
  run_once: true

- name: disabling updates for cluster core components
  ansible.builtin.shell: |
    apt-mark hold containerd.io kubeadm kubectl kubelet
