- name: install rook-ceph (1/3)
  ansible.builtin.copy:
    src: ./templates/helm-rook-values.yaml
    dest: /tmp/helm-rook-values.yaml
    owner: root
    group: root
    mode: '0644'
  run_once: true

- name: install rook-ceph (2/3)
  ansible.builtin.template:
    src: ./templates/helm-rook-cluster-values.j2
    dest: /tmp/helm-rook-cluster-values.yaml
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: install rook-ceph (3/3)
  ansible.builtin.shell: |
    helm --kubeconfig /etc/rancher/rke2/rke2.yaml repo add rook-release https://charts.rook.io/release
    helm --kubeconfig /etc/rancher/rke2/rke2.yaml repo update
    helm --kubeconfig /etc/rancher/rke2/rke2.yaml upgrade -i rook-ceph -n rook-ceph --create-namespace --wait --atomic --version v1.10.8 rook-release/rook-ceph -f /tmp/helm-rook-values.yaml
    helm --kubeconfig /etc/rancher/rke2/rke2.yaml upgrade -i rook-ceph-cluster -n rook-ceph --wait --atomic --version v1.10.8 rook-release/rook-ceph-cluster -f /tmp/helm-rook-cluster-values.yaml
  run_once: true

- name: pause for 1 minutes to rook-ceph completely up
  ansible.builtin.pause:
    minutes: 1
    prompt: "Pause for 1 minutes to rook-ceph completely up"

- name: reveal ceph dashboard password (1/2)
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl --kubeconfig=/etc/rancher/rke2/rke2.yaml get secrets rook-ceph-dashboard-password -n rook-ceph -o=jsonpath='{.data.password}' | base64 -d
  register: rook_ceph_dashboard_password
  run_once: true

- name: reveal ceph dashboard password (2/2)
  debug:
    var: rook_ceph_dashboard_password.stdout_lines
  run_once: true