- name: labeling worker nodes (1/2)
  ansible.builtin.template:
    src: ./templates/labeling-nodes-sh.j2
    dest: /tmp/labeling-nodes.sh
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: labeling worker nodes (2/2)
  ansible.builtin.shell: |
    bash /tmp/labeling-nodes.sh
  run_once: true

- name: install helm
  ansible.builtin.shell: |
    curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    chmod 700 /tmp/get_helm.sh
    /tmp/get_helm.sh
  run_once: true

- name: install metallb load balancer (1/3)
  ansible.builtin.shell: |
    helm repo add metallb https://metallb.github.io/metallb
    helm repo update
  when: metallb|bool == true
  run_once: true

- name: install metallb load balancer (2/3)
  ansible.builtin.template:
    src: ./templates/helm-metallb-values.j2
    dest: /tmp/helm-metallb-values.yaml
    owner: root
    group: root
    mode: "0644"
  when: metallb|bool == true
  run_once: true

- name: install metallb load balancer (3/3)
  ansible.builtin.shell: |
    helm upgrade -i metallb -n metallb-system --create-namespace --wait --atomic --version 0.13.7 metallb/metallb -f /tmp/helm-metallb-values.yaml
  when: metallb|bool == true
  run_once: true

- name: install traefik ingress (1/3)
  ansible.builtin.shell: |
    helm repo add traefik https://traefik.github.io/charts
    helm repo update
  when: traefik_ingress|bool == true
  run_once: true

- name: install traefik ingress (2/3)
  ansible.builtin.template:
    src: ./templates/helm-traefik-values.j2
    dest: /tmp/helm-traefik-values.yaml
    owner: root
    group: root
    mode: "0644"
  when: traefik_ingress|bool == true
  run_once: true

- name: install traefik ingress (3/3)
  ansible.builtin.shell: |
    helm upgrade -i traefik-ingress -n ingress-system --create-namespace --wait --atomic --version 20.8.0 traefik/traefik -f /tmp/helm-traefik-values.yaml
  when: traefik_ingress|bool == true
  run_once: true

- name: install metrics-server (1/2)
  ansible.builtin.template:
    src: ./templates/metrics-server-yml.j2
    dest: /tmp/metrics-server.yml
    owner: root
    group: root
    mode: "0644"
  when: metrics_server|bool == true
  run_once: true

- name: install metrics-server (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/metrics-server.yml
  when: metrics_server|bool == true
  run_once: true

- name: apply etcd backup cronjob (1/2)
  ansible.builtin.template:
    src: ./templates/cj-etcd-backup.j2
    dest: /tmp/cj-etcd-backup.yml
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: apply etcd backup cronjob (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/cj-etcd-backup.yml
  run_once: true