- name: labeling worker nodes (1/2)
  ansible.builtin.template:
    src: ./templates/labeling-nodes-sh.j2
    dest: /tmp/labeling-nodes.sh
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: labeling worker nodes (2/2)
  ansible.builtin.shell: |
    bash /tmp/labeling-nodes.sh
  run_once: true

- name: install helm
  ansible.builtin.shell: |
    curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    chmod 700 /tmp/get_helm.sh
    /tmp/get_helm.sh
  run_once: true

- name: install metallb load balancer (1/4)
  ansible.builtin.template:
    src: ./templates/helm-metallb-values.j2
    dest: /tmp/helm-metallb-values.yaml
    owner: root
    group: root
    mode: "0644"
  when: metallb|bool == true
  run_once: true

- name: install metallb load balancer (2/4)
  ansible.builtin.shell: |
    helm repo add metallb https://metallb.github.io/metallb
    helm repo update
    helm upgrade -i metallb -n metallb-system --create-namespace --wait --atomic --version 0.13.7 metallb/metallb -f /tmp/helm-metallb-values.yaml
  when: metallb|bool == true
  run_once: true

- name: install metallb load balancer (3/4)
  ansible.builtin.template:
    src: ./templates/metallb-pool.j2
    dest: /tmp/metallb-pool.yml
    owner: root
    group: root
    mode: "0644"
  when: metallb|bool == true
  run_once: true

- name: install metallb load balancer (4/4)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/metallb-pool.yml
  when: metallb|bool == true
  run_once: true

- name: install traefik ingress (1/2)
  ansible.builtin.template:
    src: ./templates/helm-traefik-values.j2
    dest: /tmp/helm-traefik-values.yaml
    owner: root
    group: root
    mode: "0644"
  when: traefik_ingress|bool == true
  run_once: true

- name: install traefik ingress (2/2)
  ansible.builtin.shell: |
    helm repo add traefik https://traefik.github.io/charts
    helm repo update
    helm upgrade -i traefik-ingress -n ingress-system --create-namespace --wait --atomic --version 20.8.0 traefik/traefik -f /tmp/helm-traefik-values.yaml
  when: traefik_ingress|bool == true
  run_once: true

- name: apply traefik dashboard ingress (1/2)
  ansible.builtin.template:
    src: ./templates/traefik-dashboard-ingress.j2
    dest: /tmp/traefik-dashboard-ingress.yml
    owner: root
    group: root
    mode: "0644"
  when: traefik_ingress|bool == true
  run_once: true

- name: apply traefik dashboard ingress (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/traefik-dashboard-ingress.yml
  when: traefik_ingress|bool == true
  run_once: true

- name: install rook-ceph (1/3)
  ansible.builtin.copy:
    src: ./templates/helm-rook-values.yaml
    dest: /tmp/helm-rook-values.yaml
    owner: root
    group: root
    mode: '0644'
  when: rook_ceph|bool == true
  run_once: true

- name: install rook-ceph (2/3)
  ansible.builtin.template:
    src: ./templates/helm-rook-cluster-values.j2
    dest: /tmp/helm-rook-cluster-values.yaml
    owner: root
    group: root
    mode: "0644"
  when: rook_ceph|bool == true
  run_once: true

- name: install rook-ceph (3/3)
  ansible.builtin.shell: |
    helm repo add rook-release https://charts.rook.io/release
    helm repo update
    helm upgrade -i rook-ceph -n rook-ceph --create-namespace --wait --atomic --version v1.10.8 rook-release/rook-ceph -f /tmp/helm-rook-values.yaml
    helm upgrade -i rook-ceph-cluster -n rook-ceph --wait --atomic --version v1.10.8 rook-release/rook-ceph-cluster -f /tmp/helm-rook-cluster-values.yaml
  when: rook_ceph|bool == true
  run_once: true

- name: install metrics-server (1/2)
  ansible.builtin.template:
    src: ./templates/metrics-server-yml.j2
    dest: /tmp/metrics-server.yml
    owner: root
    group: root
    mode: "0644"
  when: metrics_server|bool == true
  run_once: true

- name: install metrics-server (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/metrics-server.yml
  when: metrics_server|bool == true
  run_once: true

- name: apply etcd backup cronjob (1/2)
  ansible.builtin.template:
    src: ./templates/cj-etcd-backup.j2
    dest: /tmp/cj-etcd-backup.yml
    owner: root
    group: root
    mode: "0644"
  run_once: true

- name: apply etcd backup cronjob (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/cj-etcd-backup.yml
  run_once: true

- name: pause for 1 minutes to rook-ceph completely up
  ansible.builtin.pause:
    minutes: 1
    prompt: "Pause for 1 minutes to rook-ceph completely up" 

- name: install kubernetes dashboard (1/4)
  ansible.builtin.copy:
    src: ./templates/kube_dash_sa.yaml
    dest: /tmp/kube_dash_sa.yaml
    owner: root
    group: root
    mode: '0644'
  when: k8s_dash|bool == true
  run_once: true

- name: install kubernetes dashboard (2/4)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/kube_dash_sa.yaml
  when: k8s_dash|bool == true
  run_once: true

- name: install kubernetes dashboard (3/4)
  ansible.builtin.template:
    src: ./templates/helm-k8s-dash-values.j2
    dest: /tmp/helm-k8s-dash-values.yaml
    owner: root
    group: root
    mode: "0644"
  when: k8s_dash|bool == true
  run_once: true

- name: install kubernetes dashboard (4/4)
  ansible.builtin.shell: |
    helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
    helm repo update
    helm upgrade -i kubernetes-dashboard -n kubernetes-dashboard --wait --atomic --version 6.0.0 kubernetes-dashboard/kubernetes-dashboard -f /tmp/helm-k8s-dash-values.yaml
  when: k8s_dash|bool == true
  run_once: true

- name: reveal kubernetes dashboard token (1/2)
  ansible.builtin.shell: |
    kubectl -n kubernetes-dashboard get secret secret-sa-k8s-dash -o=jsonpath='{.data.token}' | base64 -d
  register: kubernetes_dashboard_token
  when: k8s_dash|bool == true
  run_once: true

- name: reveal kubernetes dashboard token (2/2)
  debug:
    var: kubernetes_dashboard_token.stdout_lines
  when: k8s_dash|bool == true
  run_once: true

- name: reveal ceph dashboard password (1/2)
  ansible.builtin.shell: |
    kubectl get secrets rook-ceph-dashboard-password -n rook-ceph -o=jsonpath='{.data.password}' | base64 -d
  register: rook_ceph_dashboard_password
  when: rook_ceph|bool == true
  run_once: true

- name: reveal ceph dashboard password (2/2)
  debug:
    var: rook_ceph_dashboard_password.stdout_lines
  when: rook_ceph|bool == true
  run_once: true
